language: python
python:
  # - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip --no-cache-dir install -r requirements.txt
  - pip --no-cache-dir install -r test-requirements.txt
# command to run tests
script: "nosetests && pylint src/azimutt/containers_density"
